// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ConsultationSubscriptionController from "./consultation_subscription_controller"
application.register("consultation-subscription", ConsultationSubscriptionController)

import DarkmodeController from "./darkmode_controller"
application.register("darkmode", DarkmodeController)

import DragDropController from "./drag_drop_controller"
application.register("drag-drop", DragDropController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import LoadingAnimationController from "./loading_animation_controller"
application.register("loading-animation", LoadingAnimationController)

import PartialRenderingController from "./partial_rendering_controller"
application.register("partial-rendering", PartialRenderingController)

import SearchCardioController from "./search_cardio_controller"
application.register("search-cardio", SearchCardioController)

import TotoController from "./toto_controller"
application.register("toto", TotoController)
