// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ConsultationSubscriptionController from "./consultation_subscription_controller"
application.register("consultation-subscription", ConsultationSubscriptionController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import PartialRenderingController from "./partial_rendering_controller"
application.register("partial-rendering", PartialRenderingController)

import TotoController from "./toto_controller"
application.register("toto", TotoController)
