class CreateCardiologists < ActiveRecord::Migration[7.0]
  def change
    create_table :cardiologists do |t|
      t.string :"Type d'identifiant PP"
      t.string :"Identifiant PP"
      t.string :"Identification nationale PP"
      t.string :"Code civilité d'exercice"
      t.string :"Libellé civilité d'exercice"
      t.string :"Code civilité"
      t.string :"Libellé civilité"
      t.string :"Nom d'exercice"
      t.string :"Prénom d'exercice"
      t.string :"Code profession"
      t.string :"Libellé profession"
      t.string :"Code catégorie professionnelle"
      t.string :"Libellé catégorie professionnelle"
      t.string :"Code type savoir-faire"
      t.string :"Libellé type savoir-faire"
      t.string :"Code savoir-faire"
      t.string :"Libellé savoir-faire"
      t.string :"Code mode exercice"
      t.string :"Libellé mode exercice"
      t.string :"Numéro SIRET site"
      t.string :"Numéro SIREN site"
      t.string :"Numéro FINESS site"
      t.string :"Numéro FINESS établissement juridique"
      t.string :"Identifiant technique de la structure"
      t.string :"Raison sociale site"
      t.string :"Enseigne commerciale site"
      t.string :"Complément destinataire"
      t.string :"Complément point géographique"
      t.string :"Numéro Voie"
      t.string :"Indice répétition voie"
      t.string :"Code type de voie"
      t.string :"Libellé type de voie"
      t.string :"Libellé Voie"
      t.string :"Mention distribution"
      t.string :"Bureau cedex"
      t.string :"Code postal"
      t.string :"Code commune"
      t.string :"Libellé commune"
      t.string :"Code pays"
      t.string :"Libellé pays"
      t.string :"Téléphone"
      t.string :"Téléphone 2"
      t.string :"Télécopie"
      t.string :"Adresse e-mail"
      t.string :"Code Département"
      t.string :"Libellé Département"
      t.string :"Ancien identifiant de la structure"
      t.string :"Autorité d'enregistrement"
      t.string :"Code secteur d'activité"
      t.string :"Libellé secteur d'activité"
      t.string :"Code section tableau pharmaciens"
      t.string :"Libellé section tableau pharmaciens"
      t.string :"Code rôle"
      t.string :"Libellé rôle"
      t.string :"Code genre activité"
      t.string :"Libellé genre activité"

      t.timestamps
    end
  end
end
